export const ROUTES = {
  HOME: '/',
  EXPLORE_NATURE: '/explore/nature',
  EXPLORE_EATS: '/explore/eats',
  EXPLORE_NIGHTLIFE: '/explore/nightlife',
  EXPLORE_ACTION: '/explore/action',
  EVENTS: '/events',
  EVENT_DETAILS: (id = ':id') => `/events/${id}`,
  PLACE_DETAILS: (id = ':id') => `/places/${id}`,
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  FORGOT_PASSWORD: '/auth/forgot-password',
  PROFILE: '/profile',
  FAVORITES: '/profile/favorites',
  MY_REVIEWS: '/profile/my-reviews',
  DASHBOARD: '/dashboard',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_PLACES: '/admin/places',
  ADMIN_EVENTS: '/admin/events',
  ADMIN_USERS: '/admin/users',
};